import { lazy, Suspense, useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, Code2, Link, Mail, Menu, X, MapPin, ExternalLink, Terminal as TerminalIcon } from 'lucide-react'
import './App.css'
import { portfolio, type Project } from './data/portfolio'

const HeroScene = lazy(() => import('./components/3d/HeroScene'))
const navItems = [['about', 'About'], ['education', 'Education'], ['projects', 'Projects'], ['skills', 'Skills'], ['contact', 'Contact']]

function Reveal({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) {
  const reduceMotion = useReducedMotion()
  return <motion.div className={className} initial={{ opacity: 0, y: reduceMotion ? 0 : 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: reduceMotion ? 0.2 : 0.65, delay }}>{children}</motion.div>
}

function SectionIntro({ index, eyebrow, title, detail }: { index: string; eyebrow: string; title: string; detail: string }) {
  return <div className="section-intro"><span className="section-index">{index}</span><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="section-detail">{detail}</p></div></div>
}

function Terminal() {
  return <div className="terminal" aria-label="Developer terminal status"><div className="terminal-bar"><span className="terminal-dots"><i /><i /><i /></span><span>developer@portfolio:~</span><span className="terminal-status">● online</span></div><div className="terminal-body"><p><b># who am i</b></p><p className="terminal-value">engineering_student<span className="cursor">_</span></p><p><b> focus</b></p><p className="terminal-value">software · systems · learning</p><p><b> status</b></p><p className="terminal-value green"><Check size={13} /> available for opportunities</p></div></div>
}

function ProjectCard({ project, onDetails, featured = false }: { project: Project; onDetails: () => void; featured?: boolean }) {
  return <motion.article className={`project-card ${featured ? 'featured' : ''}`} whileHover={{ y: -8 }} transition={{ type: 'spring', stiffness: 280, damping: 22 }}><div className="project-visual" style={{ '--project-accent': project.accent } as React.CSSProperties}><div className="project-visual-grid" /><div className="project-orbit orbit-one" /><div className="project-orbit orbit-two" /><span className="visual-code">{'{ build: true }'}</span><span className="visual-number">0{featured ? '1' : '2'}</span></div><div className="project-copy"><p className="eyebrow">{project.eyebrow}</p><h3>{project.title}</h3><p>{project.description}</p><div className="pills">{project.stack.map((item) => <span key={item}>{item}</span>)}</div><div className="project-footer"><button className="text-button" onClick={onDetails}>View details <ArrowUpRight size={15} /></button><a href={project.github} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} on GitHub`}><Code2 size={17} /></a></div></div></motion.article>
}

function ProjectModal({ project, onClose }: { project: Project; onClose: () => void }) {
  return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><motion.div className="project-modal" initial={{ opacity: 0, y: 24, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 24 }} onClick={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><button className="icon-button modal-close" onClick={onClose} aria-label="Close project details"><X size={19} /></button><p className="eyebrow">{project.eyebrow}</p><h2 id="project-modal-title">{project.title}</h2><p className="modal-lede">{project.description}</p><div className="modal-grid"><div><p className="eyebrow">Problem</p><p>{project.problem}</p></div><div><p className="eyebrow">Solution</p><p>{project.solution}</p></div></div><p className="eyebrow">Engineering highlights</p><ul className="highlight-list">{project.highlights.map((highlight) => <li key={highlight}><Check size={15} />{highlight}</li>)}</ul><div className="modal-actions"><a className="button secondary" href={project.github} target="_blank" rel="noreferrer">GitHub <ExternalLink size={15} /></a><a className="button primary" href={project.demo}>Open demo <ArrowUpRight size={15} /></a></div></motion.div></motion.div>
}

function App() {
  const [loading, setLoading] = useState(true)
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [activeSection, setActiveSection] = useState('about')
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const [formStatus, setFormStatus] = useState<'idle' | 'error' | 'success'>('idle')

  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 900); const onScroll = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', onScroll, { passive: true }); return () => { window.clearTimeout(timer); window.removeEventListener('scroll', onScroll) } }, [])
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: '-30% 0px -60% 0px' }); navItems.forEach(([id]) => { const section = document.getElementById(id); if (section) observer.observe(section) }); return () => observer.disconnect() }, [])
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { setFormStatus('error'); return } setFormStatus('success'); form.reset() }

  return (
    <>
      <AnimatePresence>{loading && <motion.div className="loader" initial={{ opacity: 1 }} exit={{ opacity: 0 }}><div><span className="loader-mark">YN<span>_</span></span><p>INITIALIZING PORTFOLIO<span className="loader-dots">...</span></p><div className="loader-line"><span /></div><small>SYSTEMS READY / 2026</small></div></motion.div>}</AnimatePresence>
      <header className={`navbar ${scrolled ? 'scrolled' : ''}`}><button className="brand" onClick={() => scrollTo('about')} aria-label="Back to top"><span>{portfolio.personal.initials}</span><b>{portfolio.personal.name}</b></button><button className="mobile-menu icon-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'}>{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'open' : ''}>{navItems.map(([id, label]) => <button key={id} className={activeSection === id ? 'active' : ''} onClick={() => scrollTo(id)}>{label}</button>)}<a className="resume-link" href={`${import.meta.env.BASE_URL}${portfolio.personal.resume}`}>Resume <ArrowUpRight size={14} /></a></nav></header>
      <main>
        <section className="hero section-shell" id="about"><div className="hero-copy"><div className="status-row"><span className="status-dot" /> Open to internships & opportunities</div><p className="eyebrow hero-eyebrow">{portfolio.personal.role} <span>/</span> builder in progress</p><h1>Hi, I’m <em>{portfolio.personal.name}</em><br /><span>building software</span><br />that moves ideas forward.</h1><p className="hero-description">{portfolio.personal.bio}</p><div className="hero-actions"><button className="button primary" onClick={() => scrollTo('projects')}>View my projects <ArrowDownRight size={16} /></button><button className="button secondary" onClick={() => scrollTo('contact')}>Contact me <Mail size={16} /></button></div><Terminal /></div><div className="hero-scene-wrap"><Suspense fallback={<div className="scene-fallback">Loading system map<span>...</span></div>}><HeroScene /></Suspense></div></section>
        <div className="stats-bar section-shell"><div><strong>01</strong><span>portfolio in progress</span></div><div><strong>∞</strong><span>curiosity to learn</span></div><div><strong>24/7</strong><span>problem solving mode</span></div><div><strong>2026</strong><span>open to what’s next</span></div></div>
        <section className="content-section section-shell" id="about"><Reveal><SectionIntro index="01" eyebrow="PROFILE / 01" title="A little about me" detail="The person behind the commits, questions, and experiments." /></Reveal><div className="about-grid"><Reveal delay={0.1}><div className="about-copy"><p className="large-copy">I like the part of engineering where a rough idea becomes something another person can actually use.</p><p>{portfolio.personal.bio}</p><p>Right now, I’m growing across full-stack development, system design, and the habits that make software easier to understand and maintain.</p><a className="text-button" href={`mailto:${portfolio.personal.email}`}>Start a conversation <ArrowUpRight size={15} /></a></div></Reveal><Reveal delay={0.2}><div className="profile-card"><div className="profile-head"><span className="live-indicator" /> engineering profile <TerminalIcon size={15} /></div><div className="profile-lines"><div><span>mindset</span><b>curious / methodical</b></div><div><span>interests</span><b>systems + product</b></div><div><span>currently</span><b>learning in public</b></div><div><span>looking for</span><b>meaningful problems</b></div></div><div className="profile-footer">// no shortcuts, just iterations</div></div></Reveal></div></section>
        <section className="content-section section-shell education-section" id="education"><Reveal><SectionIntro index="02" eyebrow="EDUCATION / 02" title="The foundation" detail="A timeline still being written." /></Reveal><Reveal delay={0.12}><div className="education-card"><div className="education-marker">EDU</div><div><p className="eyebrow">{portfolio.education.duration}</p><h3>{portfolio.education.degree}</h3><p className="school">{portfolio.education.school}</p><p>{portfolio.education.details}</p><div className="coursework">{portfolio.coursework.map((course) => <span key={course}>{course}</span>)}</div></div><ChevronRight className="education-arrow" /></div></Reveal></section>
        <section className="content-section section-shell" id="projects"><Reveal><SectionIntro index="03" eyebrow="SELECTED WORK / 03" title="Projects with a point of view" detail="Small systems, deliberate decisions, and room to keep improving." /></Reveal><div className="projects-grid">{portfolio.projects.map((project, index) => <Reveal key={project.title} delay={index * 0.1}><ProjectCard project={project} featured={index === 0} onDetails={() => setSelectedProject(project)} /></Reveal>)}</div></section>
        <section className="architecture-band"><div className="section-shell architecture-inner"><Reveal><p className="eyebrow">ENGINEERING NOTES / 04</p><h2>How I think<br /><span>about systems.</span></h2><p>Good software is a conversation between a clear interface, a resilient backend, and the people who have to live with both.</p><div className="architecture-points"><span><b>01</b> Make the path obvious</span><span><b>02</b> Keep complexity local</span><span><b>03</b> Leave room to grow</span></div></Reveal><Reveal delay={0.15}><div className="architecture-diagram"><div className="diagram-node node-user">USER <small>intent</small></div><div className="diagram-line vertical" /><div className="diagram-node node-api">API LAYER <small>logic</small></div><div className="diagram-split"><div className="diagram-line" /><div className="diagram-line" /></div><div className="diagram-branches"><div className="diagram-node">DATABASE <small>truth</small></div><div className="diagram-node">CLIENT <small>delight</small></div></div><div className="diagram-label">data flow / 03 nodes online</div></div></Reveal></div></section>
        <section className="content-section section-shell" id="skills"><Reveal><SectionIntro index="05" eyebrow="TOOLKIT / 05" title="Tools I use to build" detail="Technologies are levers. The problem always comes first." /></Reveal><div className="skills-grid">{portfolio.skills.map((skill, index) => <Reveal key={skill.name} delay={index * 0.03}><div className="skill-card"><span className="skill-icon">{skill.icon}</span><div><b>{skill.name}</b><small>{skill.category}</small></div><ArrowUpRight size={15} /></div></Reveal>)}</div></section>
        <section className="contact-section section-shell" id="contact"><Reveal><div className="contact-heading"><p className="eyebrow">OPEN CHANNEL / 06</p><h2>Let’s build something<br /><span>worth talking about.</span></h2><p>Have a project, opportunity, or good question? My inbox is open.</p><div className="contact-links"><a href={`mailto:${portfolio.personal.email}`}><Mail size={15} /> {portfolio.personal.email}</a><a href={portfolio.personal.github} target="_blank" rel="noreferrer"><Code2 size={15} /> GitHub</a><a href={portfolio.personal.linkedin} target="_blank" rel="noreferrer"><Link size={15} /> LinkedIn</a><span><MapPin size={15} /> {portfolio.personal.location}</span></div></div></Reveal><Reveal delay={0.15}><form className="contact-form" onSubmit={handleSubmit} noValidate><div className="form-row"><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label></div><label>Subject<input name="subject" required placeholder="What are we building?" /></label><label>Message<textarea name="message" required minLength={20} rows={5} placeholder="A few words to start..." /></label><button className="button primary" type="submit">Send message <ArrowUpRight size={16} /></button>{formStatus === 'error' && <p className="form-message error">Please complete each field. Messages should be at least 20 characters.</p>}{formStatus === 'success' && <p className="form-message success"><Check size={15} /> Message prepared. Connect your email service to send it.</p>}</form></Reveal></section>
      </main>
      <footer className="footer section-shell"><span>© 2026 {portfolio.personal.name}</span><span>engineer in progress · built with intention</span><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} aria-label="Back to top">Back to top <ArrowUpRight size={14} /></button></footer>
      <AnimatePresence>{selectedProject && <ProjectModal project={selectedProject} onClose={() => setSelectedProject(null)} />}</AnimatePresence>
    </>
  )
}

export default App
